var gamepadManifest = {
    buttons:[
        {
            // start button to start game
            id:9,
            keyCode:32,
            keydown:false,
            keyup:true,
            gameState:0
        },
        {
            // fire button
            id:0,
            keyCode:32,
            keydown:true,
            keyup:true,
            gameState:1
        },
        {
            // flip button
            id:1,
            keyCode:16,
            keydown:true,
            keyup:true,
            gameState:1
        },
        {
            // select initial in highscore board
            id:0,
            keyCode:32,
            keydown:true,
            keyup:true,            
            gameState:2
        },
        {
            // start button to go back to main on game over
            id:9,
            keyCode:32,
            keydown:false,            
            keyup:true,
            gameState:3
        }
    ],
    joystick:[
        {
            keyCode:40,
            clipping:true,
            axis:1,
            range:[0.7,1.0],
            gameState:1
        },
        {
            keyCode:38,
            clipping:true,
            axis:1,
            range:[-1.0,-0.7],
            gameState:1
        },
        {
            keyCode:37,
            clipping:true,
            axis:0,
            range:[-1.0,-0.7],
            gameState:1
        },
        {
            keyCode:39,
            clipping:true,
            axis:0,
            range:[0.7,1.0],
            gameState:1
        },
        {
            keyCode:40,
            clipping:false,
            axis:1,
            range:[0.7,1.0],
            gameState:2
        },
        {
            keyCode:38,
            clipping:false,
            axis:1,
            range:[-1.0,-0.7],
            gameState:2
        },
        {
            keyCode:37,
            clipping:false,
            axis:0,
            range:[-1.0,-0.7],
            gameState:2
        },
        {
            keyCode:39,
            clipping:false,
            axis:0,
            range:[0.7,1.0],
            gameState:2
        }
    ]
};