// Game asset manifest
var gameManifest = [
    {
        src:"lib/ui.json",
        forSpritesheet:"ui"
    },
    {
        src:"lib/ui.png",
        id:"ui"
    }, 
    {
        src:"lib/charset30.json",
        forSpritesheet:"charset30"
    },
    {
        src:"lib/charset30.png",
        id:"charset30"
    },
    {
        src:"lib/charset80.json",
        forSpritesheet:"charset80"
    },
    {
        src:"lib/charset80.png",
        id:"charset80"
    },
    {
        src:"lib/assets.json",
        forSpritesheet:"assets"
    },
    {
        src:"lib/assets.png",
        id:"assets"
    },
    {
        src:"lib/bossExplosion.ogg",
        id:"bossExplosion",
        data:4
    },
    {
        src:"lib/miniBossExplosion.ogg",
        id:"miniBossExplosion",
        data:4
    },
    {
        src:"lib/flipIn.ogg",
        id:"flipIn",
        data:4
    },
    {
        src:"lib/flipOut.ogg",
        id:"flipOut",
        data:4
    },    
    {
        src:"lib/bounce.ogg",
        id:"bounce",
        data:4
    },
    {
        src:"lib/double.ogg",
        id:"double",
        data:4
    },
    {
        src:"lib/enemyHit.ogg",
        id:"enemyHit",
        data:4
    },
    {
        src:"lib/enemyShoot.ogg",
        id:"enemyShoot",
        data:4
    },
    {
        src:"lib/explosion1.ogg",
        id:"explosion1",
        data:4
    },
    {
        src:"lib/explosion2.ogg",
        id:"explosion2",
        data:4
    },
    {
        src:"lib/explosion3.ogg",
        id:"explosion3",
        data:4
    },
    {
        src:"lib/explosion4.ogg",
        id:"explosion4",
        data:4
    },
    {
        src:"lib/heavy.ogg",
        id:"heavy",
        data:4
    },
    {
        src:"lib/hitWithShield.ogg",
        id:"hitWithShield",
        data:4
    },
    {
        src:"lib/interface.ogg",
        id:"interface",
        data:4
    },
    {
        src:"lib/laser.ogg",
        id:"laser",
        data:4
    },
    {
        src:"lib/level.ogg",
        id:"level",
        data:4
    },
    {
        src:"lib/losePoints.ogg",
        id:"losePoints",
        data:4
    },
    {
        src:"lib/playerHit.ogg",
        id:"playerHit",
        data:4
    },
    {
        src:"lib/playerEnter.ogg",
        id:"playerEnter",
        data:4
    },
    {
        src:"lib/powerupAppear.ogg",
        id:"powerupAppear",
        data:4
    },
    {
        src:"lib/powerupPickup.ogg",
        id:"powerupPickup",
        data:4
    },
    {
        src:"lib/rapid.ogg",
        id:"rapid",
        data:4
    },
    {
        src:"lib/single.ogg",
        id:"single",
        data:4
    },
    {
        src:"lib/spread.ogg",
        id:"spread",
        data:4
    },
    {
        src:"lib/superDouble.ogg",
        id:"superDouble",
        data:4
    },
    {
        src:"lib/superSpread.ogg",
        id:"superSpread",
        data:4
    },
    {
        src:"lib/warning.ogg",
        id:"warning",
        data:4
    },
];
