// Game asset manifest
var gameManifest = [
    {
        src:"lib/ui.json",
        forSpritesheet:"ui"
    },
    {
        src:"lib/ui.png",
        id:"ui"
    }, 
    {
        src:"lib/charset30.json",
        forSpritesheet:"charset30"
    },
    {
        src:"lib/charset30.png",
        id:"charset30"
    },
    {
        src:"lib/charset80.json",
        forSpritesheet:"charset80"
    },
    {
        src:"lib/charset80.png",
        id:"charset80"
    },
    {
        src:"lib/assets.json",
        forSpritesheet:"assets"
    },
    {
        src:"lib/assets.png",
        id:"assets"
    }
    /*,
    {
        src:"lib/boing.ogg",
        id:"boing",
        data:4
    } */   
];
